PUT http://localhost:3000/api/notice/8 HTTP/1.1
Content-Type: application/json

{  
    "userId":1,
    "notice":"Java op",
    "description":"Operators are used to perform operations on variables and values. In the example below, we use the + operator to add together two values."
}